services:
  app:
    build: 
      dockerfile: app.Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - ./app:/app
    healthcheck:
      test: ["CMD", "ruby", "-e", "require 'socket'; TCPSocket.new('localhost', 4567).close rescue exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
