services:
  app:
    build: 
      dockerfile: app.Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - ./app:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567"]
      interval: 30s
      timeout: 10s
      retries: 3
